### ISSUE TITLE
Write access request

### ISSUE THREAD

**Issue by lcolladotor** [lmweber/BestPracticesST-images#1]
Hi Lukas,

Could you give me write access to this repo? I just made 1 minor fix to https://github.com/lmweber/BestPracticesST-resources/blob/main/spatialLIBD_demo/www/documentation_spe.md in relation to https://github.com/LieberInstitute/Visium_SPG_AD/commit/bbe31072aedf5ae046e421f9d3c93bebd8dbfd4a and `spatialLIBD` updates.

Thanks,
Leo

**Comment by lmweber** [comment]
Done, thanks!

**Comment by lcolladotor** [comment]
Thanks Lukas!

This was the commit I mentioned above: https://github.com/lmweber/BestPracticesST-resources/commit/ef9f3caec70bb842906fe3b21ea12172633af777

**Comment by lmweber** [comment]
Ah good to know, thanks!
